version: '2.1'
services:
  picaditos-api:
    depends_on:
      - picaditos-web 
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      TEAMS_URL: 'teams-ms'
      TEAMS_PORT: '4002'
      TEAMS_ENTRY: 'teams'

      LOGIN_URL: 'login-ms'
      LOGIN_PORT: '4001'
      LOGIN_ENTRY: 'auth/'

      MATCHES_URL: 'matches-ms'
      MATCHES_PORT: '4004'
      MATCHES_ENTRY: 'api/matches'

      COURTS_URL: 'courts-ms'
      COURTS_PORT: '4005'
      COURTS_ENTRY: 'courts'

      MESSAGES_URL: 'messages-ms'
      MESSAGES_PORT: '4003'
      MESSAGES_ENTRY: 'message'


    ports:
      - '5000:5000'
