version: '2.1'
services:
  picaditos-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      TEAMS_URL: '192.168.99.101'
      TEAMS_PORT: '4002'
      TEAMS_ENTRY: 'equipos'

      LOGIN_URL: '192.168.99.101'
      LOGIN_PORT: '4001'
      LOGIN_ENTRY: 'auth/'

      MATCHES_URL: '192.168.99.101'
      MATCHES_PORT: '4004'
      MATCHES_ENTRY: 'api/matches'

      COURTS_URL: '192.168.99.101'
      COURTS_PORT: '4005'
      COURTS_ENTRY: 'courts'

      MESSAGES_URL: '192.168.99.101'
      MESSAGES_PORT: '4003'
      MESSAGES_ENTRY: 'message'


    ports:
      - '5000:5000'
