version: '2.1'
services:
  picaditos-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      TEAMS_URL: '192.168.99.102'
      TEAMS_PORT: '4002'
      TEAMS_ENTRY: 'equipos'
    ports:
      - '5000:5000'
